const WEF_SKILL_GROUPS = [
  { group: "Manual dexterity, endurance and precision", skills: ["Dexterity", "Strength and stamina", "Flexibility and coordination"] },
  { group: "Sensory-processing abilities", skills: ["Visual abilities", "Auditory abilities", "Information-processing abilities", "Spatial abilities"] },
  { group: "Creativity and problem solving", skills: ["Creative thinking", "Analytical thinking", "Systems thinking"] },
  { group: "Mathematical and statistical thinking", skills: ["Number facility", "Calculating and estimating", "Algebraic facility", "Data analysis and mathematical modelling"] },
  { group: "Speaking, writing and languages", skills: ["Reading", "Speaking", "Writing", "Editing", "Multi-lingualism"] },
  { group: "Talent management", skills: ["Skill evaluation", "Talent planning and development"] },
  { group: "Operations and logistics", skills: ["Coordination and time management", "Project management", "Supply-chain management"] },
  { group: "Financial management", skills: ["Accounting", "Finance"] },
  { group: "Quality management", skills: ["Quality assurance", "Quality control", "Risk management"] },
  { group: "Marketing and media", skills: ["Sales, communication and marketing of products and services", "Digital marketing"] },
  { group: "Customer experience", skills: ["Customer service", "Customer relationship management"] },
  { group: "Technology literacy", skills: ["Collaboration and productivity software", "Manufacturing technologies", "Installation"] },
  { group: "Programming", skills: ["Functional programming", "Object-oriented programming", "Computational thinking"] },
  { group: "Design and user experience", skills: ["Human-technology interaction", "Mobile development", "Web development"] },
  { group: "Networks and cybersecurity", skills: ["Computer hardware and networking", "Cybersecurity and application security", "Cloud computing"] },
  { group: "Artificial intelligence and big data", skills: ["Data mining", "Supervised learning", "Unsupervised learning"] },
  { group: "Motivation and self-awareness", skills: ["Internal self-awareness", "External self-awareness", "Self-control", "Working independently", "Initiative"] },
  { group: "Curiosity and lifelong learning", skills: ["Curiosity", "Willingness to learn"] },
  { group: "Dependability and attention to detail", skills: ["Meeting commitments and deadlines", "Time management and prioritisation", "Attention to detail", "Assuming responsibility"] },
  { group: "Resilience, flexibility and agility", skills: ["Frustration management", "Stress management", "Adaptation to change", "Persistence"] },
  { group: "Empathy and active listening", skills: ["Empathy", "Asking questions", "Giving and receiving feedback"] },
  { group: "Service orientation", skills: ["Following instructions and procedures", "Assisting and supporting co-workers"] },
  { group: "Teaching, mentoring and coaching", skills: ["Teaching", "Mentoring", "Coaching"] },
  { group: "Leadership and social influence", skills: ["Persuasion and negotiation", "Liaising, networking and exchanging information", "Building trust"] },
  { group: "Civic responsibility", skills: ["Ethical leadership", "Social justice", "Social-cultural awareness", "Technology ethics"] },
  { group: "Environmental stewardship", skills: ["Environmental awareness", "Sustainable and efficient resource usage", "Adopting green technologies"] }
];

const WEF_SKILLS = WEF_SKILL_GROUPS.flatMap(group => group.skills);

const WEF_SKILL_GROUP_TRANSLATIONS = {
  "Manual dexterity, endurance and precision": "ความคล่องแคล่ว ความทนทาน และความแม่นยำ",
  "Sensory-processing abilities": "ความสามารถในการประมวลผลทางประสาทสัมผัส",
  "Creativity and problem solving": "ความคิดสร้างสรรค์และการแก้ปัญหา",
  "Mathematical and statistical thinking": "การคิดเชิงคณิตศาสตร์และสถิติ",
  "Speaking, writing and languages": "การพูด การเขียน และภาษา",
  "Talent management": "การบริหารบุคลากรและศักยภาพ",
  "Operations and logistics": "การดำเนินงานและโลจิสติกส์",
  "Financial management": "การบริหารการเงิน",
  "Quality management": "การบริหารคุณภาพ",
  "Marketing and media": "การตลาดและสื่อ",
  "Customer experience": "ประสบการณ์ลูกค้า",
  "Technology literacy": "ความรู้เท่าทันเทคโนโลยี",
  "Programming": "การเขียนโปรแกรม",
  "Design and user experience": "การออกแบบและประสบการณ์ผู้ใช้",
  "Networks and cybersecurity": "เครือข่ายและความมั่นคงปลอดภัยไซเบอร์",
  "Artificial intelligence and big data": "ปัญญาประดิษฐ์และข้อมูลขนาดใหญ่",
  "Motivation and self-awareness": "แรงจูงใจและการตระหนักรู้ตนเอง",
  "Curiosity and lifelong learning": "ความใฝ่รู้และการเรียนรู้ตลอดชีวิต",
  "Dependability and attention to detail": "ความน่าเชื่อถือและความใส่ใจรายละเอียด",
  "Resilience, flexibility and agility": "ความยืดหยุ่น การปรับตัว และความคล่องตัว",
  "Empathy and active listening": "ความเข้าอกเข้าใจและการฟังอย่างตั้งใจ",
  "Service orientation": "การมุ่งเน้นการบริการ",
  "Teaching, mentoring and coaching": "การสอน การเป็นพี่เลี้ยง และการโค้ช",
  "Leadership and social influence": "ภาวะผู้นำและอิทธิพลทางสังคม",
  "Civic responsibility": "ความรับผิดชอบต่อสังคม",
  "Environmental stewardship": "การดูแลรักษาสิ่งแวดล้อม"
};

const WEF_SKILL_TRANSLATIONS = {
  "Dexterity": "ความคล่องแคล่วในการใช้มือ",
  "Strength and stamina": "ความแข็งแรงและความทนทาน",
  "Flexibility and coordination": "ความยืดหยุ่นและการประสานงานของร่างกาย",
  "Visual abilities": "ความสามารถด้านการมองเห็น",
  "Auditory abilities": "ความสามารถด้านการได้ยิน",
  "Information-processing abilities": "ความสามารถในการประมวลผลข้อมูล",
  "Spatial abilities": "ความสามารถด้านมิติสัมพันธ์",
  "Creative thinking": "การคิดสร้างสรรค์",
  "Analytical thinking": "การคิดวิเคราะห์",
  "Systems thinking": "การคิดเชิงระบบ",
  "Number facility": "ความคล่องแคล่วด้านตัวเลข",
  "Calculating and estimating": "การคำนวณและการประมาณค่า",
  "Algebraic facility": "ทักษะด้านพีชคณิต",
  "Data analysis and mathematical modelling": "การวิเคราะห์ข้อมูลและการสร้างแบบจำลองทางคณิตศาสตร์",
  "Reading": "การอ่าน",
  "Speaking": "การพูด",
  "Writing": "การเขียน",
  "Editing": "การตรวจแก้เนื้อหา",
  "Multi-lingualism": "ความสามารถในการใช้หลายภาษา",
  "Skill evaluation": "การประเมินทักษะ",
  "Talent planning and development": "การวางแผนและพัฒนาบุคลากร",
  "Coordination and time management": "การประสานงานและการบริหารเวลา",
  "Project management": "การบริหารโครงการ",
  "Supply-chain management": "การจัดการโซ่อุปทาน",
  "Accounting": "การบัญชี",
  "Finance": "การเงิน",
  "Quality assurance": "การประกันคุณภาพ",
  "Quality control": "การควบคุมคุณภาพ",
  "Risk management": "การบริหารความเสี่ยง",
  "Sales, communication and marketing of products and services": "การขาย การสื่อสาร และการตลาดสินค้าและบริการ",
  "Digital marketing": "การตลาดดิจิทัล",
  "Customer service": "การบริการลูกค้า",
  "Customer relationship management": "การบริหารความสัมพันธ์กับลูกค้า",
  "Collaboration and productivity software": "ซอฟต์แวร์เพื่อการทำงานร่วมกันและเพิ่มผลิตภาพ",
  "Manufacturing technologies": "เทคโนโลยีการผลิต",
  "Installation": "การติดตั้ง",
  "Functional programming": "การเขียนโปรแกรมเชิงฟังก์ชัน",
  "Object-oriented programming": "การเขียนโปรแกรมเชิงวัตถุ",
  "Computational thinking": "การคิดเชิงคำนวณ",
  "Human-technology interaction": "ปฏิสัมพันธ์ระหว่างมนุษย์กับเทคโนโลยี",
  "Mobile development": "การพัฒนาแอปพลิเคชันบนอุปกรณ์เคลื่อนที่",
  "Web development": "การพัฒนาเว็บไซต์",
  "Computer hardware and networking": "ฮาร์ดแวร์คอมพิวเตอร์และระบบเครือข่าย",
  "Cybersecurity and application security": "ความมั่นคงปลอดภัยไซเบอร์และแอปพลิเคชัน",
  "Cloud computing": "การประมวลผลแบบคลาวด์",
  "Data mining": "การทำเหมืองข้อมูล",
  "Supervised learning": "การเรียนรู้ของเครื่องแบบมีผู้สอน",
  "Unsupervised learning": "การเรียนรู้ของเครื่องแบบไม่มีผู้สอน",
  "Internal self-awareness": "การตระหนักรู้ตนเองจากภายใน",
  "External self-awareness": "การตระหนักรู้ผลกระทบของตนที่มีต่อผู้อื่น",
  "Self-control": "การควบคุมตนเอง",
  "Working independently": "การทำงานอย่างอิสระ",
  "Initiative": "ความคิดริเริ่ม",
  "Curiosity": "ความใฝ่รู้",
  "Willingness to learn": "ความเต็มใจที่จะเรียนรู้",
  "Meeting commitments and deadlines": "การรักษาคำมั่นและกำหนดเวลา",
  "Time management and prioritisation": "การบริหารเวลาและจัดลำดับความสำคัญ",
  "Attention to detail": "ความใส่ใจรายละเอียด",
  "Assuming responsibility": "การรับผิดชอบหน้าที่",
  "Frustration management": "การจัดการความคับข้องใจ",
  "Stress management": "การจัดการความเครียด",
  "Adaptation to change": "การปรับตัวต่อการเปลี่ยนแปลง",
  "Persistence": "ความมุ่งมั่นไม่ย่อท้อ",
  "Empathy": "ความเข้าอกเข้าใจผู้อื่น",
  "Asking questions": "การตั้งคำถาม",
  "Giving and receiving feedback": "การให้และรับข้อเสนอแนะ",
  "Following instructions and procedures": "การปฏิบัติตามคำแนะนำและขั้นตอน",
  "Assisting and supporting co-workers": "การช่วยเหลือและสนับสนุนเพื่อนร่วมงาน",
  "Teaching": "การสอน",
  "Mentoring": "การเป็นพี่เลี้ยง",
  "Coaching": "การโค้ช",
  "Persuasion and negotiation": "การโน้มน้าวและการเจรจาต่อรอง",
  "Liaising, networking and exchanging information": "การประสานงาน สร้างเครือข่าย และแลกเปลี่ยนข้อมูล",
  "Building trust": "การสร้างความไว้วางใจ",
  "Ethical leadership": "ภาวะผู้นำเชิงจริยธรรม",
  "Social justice": "ความยุติธรรมทางสังคม",
  "Social-cultural awareness": "ความตระหนักด้านสังคมและวัฒนธรรม",
  "Technology ethics": "จริยธรรมด้านเทคโนโลยี",
  "Environmental awareness": "ความตระหนักด้านสิ่งแวดล้อม",
  "Sustainable and efficient resource usage": "การใช้ทรัพยากรอย่างยั่งยืนและมีประสิทธิภาพ",
  "Adopting green technologies": "การนำเทคโนโลยีสีเขียวมาใช้"
};
